x-varblock: &uidblock
  uid: "${UID:-1000}"

services:
  php-apache:
    container_name: domain_history_dev_php
    build: 
      target: dev
      args:
        <<: *uidblock
      context: .
      dockerfile: ./docker/php-apache/Dockerfile
    ports:
      - 8080:8000
      - 5173:5173
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/var/www/html:rw
    command: sh -c "php artisan serve --host=0.0.0.0 --port=8000 & php artisan app:cache-clear; npm run dev -- --host"

  php-cli:
    container_name: domain_history_dev_php-cli
    build:
      target: dev
      args:
        <<: *uidblock
      context: .
      dockerfile: ./docker/php-cli/Dockerfile
    volumes:
      - .:/app:rw
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: domain_history_dev_mysql
    image: 'mysql:9'
    environment:
      - MYSQL_DATABASE=domain
      - MYSQL_USER=username
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql:cached
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  mysql-data:
    external: false
